Repository mmart1n/WebShopOvGUMagdeburg, pull requests merged in 2019-11, with the labels that each got.

#4 veraenderung der title
  index.html
Labels: resolved

#2 Test branch merge
  assets/css/index.css
  assets/css/vorlage.css
  index.html
  vorlage.html
Labels: awaiting-test, do-not-merge

#10 add katalog layout
  assets/css/book-layout.css
  book-layout.html
Labels: awaiting-test

#9 navbar hinzugefuegt
  vorlage.html
Labels: resolved
